version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Map frontend port
    networks:
      - my-network
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map backend port
    networks:
      - my-network
    env_file:
      - ./backend/.env

networks:
  my-network:
    driver: bridge
